//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.05.04 at 05:32:16 PM EEST
//
package eu.europa.ec.fisheries.uvms.subscription.service.execution;

/**
 * Service to execute a subscription.
 */
public interface SubscriptionExecutionService {
}
