//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.05.04 at 05:32:16 PM EEST
//
package eu.europa.ec.fisheries.uvms.subscription.service.execution;

import java.util.Map;
import java.util.stream.Collectors;

import eu.europa.ec.fisheries.uvms.subscription.service.domain.TriggeredSubscriptionDataEntity;
import eu.europa.ec.fisheries.uvms.subscription.service.domain.TriggeredSubscriptionEntity;

/**
 * Implementations of this interface are responsible for a specific kind of subscription execution
 * (e.g. email, send FA query) and the translation of data to the corresponding domain.
 */
public interface TriggeredSubscriptionExecutor {
	/**
	 * Execute a triggered subscription by its id.
	 *
	 * @param id The triggered subscription id
	 */
	void execute(Long id);

	/**
	 * Execute a triggered subscription.
	 *
	 * @param triggeredSubscription The triggered subscription to execute
	 */
	void execute(TriggeredSubscriptionEntity triggeredSubscription);

	/**
	 * Extract the data of the given triggered subscription to a convenient map.
	 *
	 * @param triggeredSubscription The triggered subscription, cannot be null
	 * @return A map view of the triggered subscription data
	 */
	default Map<String,String> toDataMap(TriggeredSubscriptionEntity triggeredSubscription) {
		return triggeredSubscription.getData().stream().collect(Collectors.toMap(TriggeredSubscriptionDataEntity::getKey, TriggeredSubscriptionDataEntity::getValue));
	}
}
