//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.05.04 at 05:32:16 PM EEST
//
package eu.europa.ec.fisheries.uvms.subscription.service.bean;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.context.Dependent;
import javax.enterprise.inject.Produces;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;

/**
 * Producers for useful XML-related objects.
 */
@Dependent
class XmlUtilitiesProducer {
	/**
	 * Produce the {@code DatatypeFactory} once, as creating anew each time it is used seems expensive.
	 *
	 * @return An application-scoped instance of the {@code DatatypeFactory}
	 */
	@Produces @ApplicationScoped
	public DatatypeFactory getDatatypeFactory() {
		try {
			return DatatypeFactory.newInstance();
		} catch (DatatypeConfigurationException e) {
			throw new IllegalStateException(e);
		}
	}
}
